Search.appendIndex(
    [
                {
            "fqsen": "\\SocketManager\\Library\\CycleDrivenManager",
            "name": "CycleDrivenManager",
            "summary": "\u5468\u671F\u30C9\u30EA\u30D6\u30F3\u30DE\u30CD\u30FC\u30B8\u30E3\u30FC\u30AF\u30E9\u30B9",
            "url": "classes/SocketManager-Library-CycleDrivenManager.html"
        },                {
            "fqsen": "\\SocketManager\\Library\\CycleDrivenManager\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "\u30B3\u30F3\u30B9\u30C8\u30E9\u30AF\u30BF",
            "url": "classes/SocketManager-Library-CycleDrivenManager.html#method___construct"
        },                {
            "fqsen": "\\SocketManager\\Library\\CycleDrivenManager\u003A\u003AisSetQueue\u0028\u0029",
            "name": "isSetQueue",
            "summary": "\u30AD\u30E5\u30FC\u306E\u8A2D\u5B9A\u3092\u691C\u67FB",
            "url": "classes/SocketManager-Library-CycleDrivenManager.html#method_isSetQueue"
        },                {
            "fqsen": "\\SocketManager\\Library\\CycleDrivenManager\u003A\u003AaddStatusUnit\u0028\u0029",
            "name": "addStatusUnit",
            "summary": "\u30B9\u30C6\u30FC\u30BF\u30B9UNIT\u306E\u8FFD\u52A0",
            "url": "classes/SocketManager-Library-CycleDrivenManager.html#method_addStatusUnit"
        },                {
            "fqsen": "\\SocketManager\\Library\\CycleDrivenManager\u003A\u003AgetQueueNameList\u0028\u0029",
            "name": "getQueueNameList",
            "summary": "\u30AD\u30E5\u30FC\u540D\u306E\u30EA\u30B9\u30C8\u53D6\u5F97",
            "url": "classes/SocketManager-Library-CycleDrivenManager.html#method_getQueueNameList"
        },                {
            "fqsen": "\\SocketManager\\Library\\CycleDrivenManager\u003A\u003AgetStatusNameList\u0028\u0029",
            "name": "getStatusNameList",
            "summary": "\u30B9\u30C6\u30FC\u30BF\u30B9\u540D\u306E\u30EA\u30B9\u30C8\u53D6\u5F97",
            "url": "classes/SocketManager-Library-CycleDrivenManager.html#method_getStatusNameList"
        },                {
            "fqsen": "\\SocketManager\\Library\\CycleDrivenManager\u003A\u003AcycleDriven\u0028\u0029",
            "name": "cycleDriven",
            "summary": "\u5468\u671F\u30C9\u30EA\u30D6\u30F3\u51E6\u7406\u306E\u5B9F\u884C",
            "url": "classes/SocketManager-Library-CycleDrivenManager.html#method_cycleDriven"
        },                {
            "fqsen": "\\SocketManager\\Library\\CycleDrivenManager\u003A\u003A\u0024queues",
            "name": "queues",
            "summary": "\u30AD\u30E5\u30FC\u30EA\u30B9\u30C8",
            "url": "classes/SocketManager-Library-CycleDrivenManager.html#property_queues"
        },                {
            "fqsen": "\\SocketManager\\Library\\IEntryUnits",
            "name": "IEntryUnits",
            "summary": "\u30B9\u30C6\u30FC\u30BF\u30B9UNIT\u767B\u9332\u306E\u30A4\u30F3\u30BF\u30D5\u30A7\u30FC\u30B9",
            "url": "classes/SocketManager-Library-IEntryUnits.html"
        },                {
            "fqsen": "\\SocketManager\\Library\\IEntryUnits\u003A\u003AgetQueueList\u0028\u0029",
            "name": "getQueueList",
            "summary": "\u30AD\u30E5\u30FC\u30EA\u30B9\u30C8\u306E\u53D6\u5F97",
            "url": "classes/SocketManager-Library-IEntryUnits.html#method_getQueueList"
        },                {
            "fqsen": "\\SocketManager\\Library\\IEntryUnits\u003A\u003AgetUnitList\u0028\u0029",
            "name": "getUnitList",
            "summary": "\u30B9\u30C6\u30FC\u30BF\u30B9UNIT\u30EA\u30B9\u30C8\u306E\u53D6\u5F97",
            "url": "classes/SocketManager-Library-IEntryUnits.html#method_getUnitList"
        },                {
            "fqsen": "\\SocketManager\\Library\\IInitSocketManager",
            "name": "IInitSocketManager",
            "summary": "SocketManager\u30AF\u30E9\u30B9\u521D\u671F\u5316\u7528\u30A4\u30F3\u30BF\u30D5\u30A7\u30FC\u30B9",
            "url": "classes/SocketManager-Library-IInitSocketManager.html"
        },                {
            "fqsen": "\\SocketManager\\Library\\IInitSocketManager\u003A\u003AgetLogWriter\u0028\u0029",
            "name": "getLogWriter",
            "summary": "\u30ED\u30B0\u30E9\u30A4\u30BF\u30FC\u306E\u53D6\u5F97",
            "url": "classes/SocketManager-Library-IInitSocketManager.html#method_getLogWriter"
        },                {
            "fqsen": "\\SocketManager\\Library\\IInitSocketManager\u003A\u003AgetSerializer\u0028\u0029",
            "name": "getSerializer",
            "summary": "\u30B7\u30EA\u30A2\u30E9\u30A4\u30B6\u30FC\u306E\u53D6\u5F97",
            "url": "classes/SocketManager-Library-IInitSocketManager.html#method_getSerializer"
        },                {
            "fqsen": "\\SocketManager\\Library\\IInitSocketManager\u003A\u003AgetUnserializer\u0028\u0029",
            "name": "getUnserializer",
            "summary": "\u30A2\u30F3\u30B7\u30EA\u30A2\u30E9\u30A4\u30B6\u30FC\u306E\u53D6\u5F97",
            "url": "classes/SocketManager-Library-IInitSocketManager.html#method_getUnserializer"
        },                {
            "fqsen": "\\SocketManager\\Library\\IInitSocketManager\u003A\u003AgetCommandDispatcher\u0028\u0029",
            "name": "getCommandDispatcher",
            "summary": "\u30B3\u30DE\u30F3\u30C9\u30C7\u30A3\u30B9\u30D1\u30C3\u30C1\u30E3\u30FC\u306E\u53D6\u5F97",
            "url": "classes/SocketManager-Library-IInitSocketManager.html#method_getCommandDispatcher"
        },                {
            "fqsen": "\\SocketManager\\Library\\IInitSocketManager\u003A\u003AgetEmergencyCallback\u0028\u0029",
            "name": "getEmergencyCallback",
            "summary": "\u7DCA\u6025\u505C\u6B62\u6642\u306E\u30B3\u30FC\u30EB\u30D0\u30C3\u30AF\u306E\u53D6\u5F97",
            "url": "classes/SocketManager-Library-IInitSocketManager.html#method_getEmergencyCallback"
        },                {
            "fqsen": "\\SocketManager\\Library\\IInitSocketManager\u003A\u003AgetUnitParameter\u0028\u0029",
            "name": "getUnitParameter",
            "summary": "UNIT\u30D1\u30E9\u30E1\u30FC\u30BF\u30A4\u30F3\u30B9\u30BF\u30F3\u30B9\u306E\u53D6\u5F97",
            "url": "classes/SocketManager-Library-IInitSocketManager.html#method_getUnitParameter"
        },                {
            "fqsen": "\\SocketManager\\Library\\IProtocolParameter",
            "name": "IProtocolParameter",
            "summary": "\u30D7\u30ED\u30C8\u30B3\u30EB\u30D1\u30E9\u30E1\u30FC\u30BF\u30A4\u30F3\u30BF\u30D5\u30A7\u30FC\u30B9",
            "url": "classes/SocketManager-Library-IProtocolParameter.html"
        },                {
            "fqsen": "\\SocketManager\\Library\\IProtocolParameter\u003A\u003AsetReceivingSize\u0028\u0029",
            "name": "setReceivingSize",
            "summary": "\u30C7\u30FC\u30BF\u53D7\u4FE1\u30B5\u30A4\u30BA\u306E\u8A2D\u5B9A",
            "url": "classes/SocketManager-Library-IProtocolParameter.html#method_setReceivingSize"
        },                {
            "fqsen": "\\SocketManager\\Library\\IProtocolParameter\u003A\u003Areceiving\u0028\u0029",
            "name": "receiving",
            "summary": "\u30C7\u30FC\u30BF\u53D7\u4FE1",
            "url": "classes/SocketManager-Library-IProtocolParameter.html#method_receiving"
        },                {
            "fqsen": "\\SocketManager\\Library\\IProtocolParameter\u003A\u003Arecv\u0028\u0029",
            "name": "recv",
            "summary": "\u30C7\u30FC\u30BF\u53D7\u4FE1",
            "url": "classes/SocketManager-Library-IProtocolParameter.html#method_recv"
        },                {
            "fqsen": "\\SocketManager\\Library\\IProtocolParameter\u003A\u003AsetSendingData\u0028\u0029",
            "name": "setSendingData",
            "summary": "\u9001\u4FE1\u30C7\u30FC\u30BF\u306E\u8A2D\u5B9A",
            "url": "classes/SocketManager-Library-IProtocolParameter.html#method_setSendingData"
        },                {
            "fqsen": "\\SocketManager\\Library\\IProtocolParameter\u003A\u003Asending\u0028\u0029",
            "name": "sending",
            "summary": "\u30C7\u30FC\u30BF\u9001\u4FE1",
            "url": "classes/SocketManager-Library-IProtocolParameter.html#method_sending"
        },                {
            "fqsen": "\\SocketManager\\Library\\IProtocolParameter\u003A\u003AgetSendData\u0028\u0029",
            "name": "getSendData",
            "summary": "\u51E6\u7406\u5BFE\u8C61\u306E\u9001\u4FE1\u30C7\u30FC\u30BF\u3092\u53D6\u5F97",
            "url": "classes/SocketManager-Library-IProtocolParameter.html#method_getSendData"
        },                {
            "fqsen": "\\SocketManager\\Library\\IUnitParameter",
            "name": "IUnitParameter",
            "summary": "UNIT\u30D1\u30E9\u30E1\u30FC\u30BF\u30A4\u30F3\u30BF\u30D5\u30A7\u30FC\u30B9",
            "url": "classes/SocketManager-Library-IUnitParameter.html"
        },                {
            "fqsen": "\\SocketManager\\Library\\IUnitParameter\u003A\u003AgetQueueName\u0028\u0029",
            "name": "getQueueName",
            "summary": "\u30AD\u30E5\u30FC\u540D\u306E\u53D6\u5F97",
            "url": "classes/SocketManager-Library-IUnitParameter.html#method_getQueueName"
        },                {
            "fqsen": "\\SocketManager\\Library\\IUnitParameter\u003A\u003AgetStatusName\u0028\u0029",
            "name": "getStatusName",
            "summary": "\u30B9\u30C6\u30FC\u30BF\u30B9\u540D\u306E\u53D6\u5F97",
            "url": "classes/SocketManager-Library-IUnitParameter.html#method_getStatusName"
        },                {
            "fqsen": "\\SocketManager\\Library\\IUnitParameter\u003A\u003AsetStatusName\u0028\u0029",
            "name": "setStatusName",
            "summary": "\u30B9\u30C6\u30FC\u30BF\u30B9\u540D\u306E\u8A2D\u5B9A",
            "url": "classes/SocketManager-Library-IUnitParameter.html#method_setStatusName"
        },                {
            "fqsen": "\\config\u0028\u0029",
            "name": "config",
            "summary": "\u8A2D\u5B9A\u5024\u306E\u53D6\u5F97",
            "url": "namespaces/default.html#function_config"
        },                {
            "fqsen": "\\SocketManager\\Library\\LogMessageEnum",
            "name": "LogMessageEnum",
            "summary": "\u30A8\u30E9\u30FC\u30E1\u30C3\u30BB\u30FC\u30B8\u5B9A\u7FA9",
            "url": "classes/SocketManager-Library-LogMessageEnum.html"
        },                {
            "fqsen": "\\SocketManager\\Library\\LogMessageEnum\u003A\u003Amessage\u0028\u0029",
            "name": "message",
            "summary": "\u30A8\u30E9\u30FC\u30E1\u30C3\u30BB\u30FC\u30B8\u306E\u53D6\u5F97",
            "url": "classes/SocketManager-Library-LogMessageEnum.html#method_message"
        },                {
            "fqsen": "\\SocketManager\\Library\\LogMessageEnum\u003A\u003Asocket\u0028\u0029",
            "name": "socket",
            "summary": "\u30BD\u30B1\u30C3\u30C8\u7528\u30A8\u30E9\u30FC\u30E1\u30C3\u30BB\u30FC\u30B8\u306E\u53D6\u5F97",
            "url": "classes/SocketManager-Library-LogMessageEnum.html#method_socket"
        },                {
            "fqsen": "\\SocketManager\\Library\\LogMessageEnum\u003A\u003Aarray\u0028\u0029",
            "name": "array",
            "summary": "\u30BD\u30B1\u30C3\u30C8\u7528\u30A8\u30E9\u30FC\u60C5\u5831\u306E\u53D6\u5F97",
            "url": "classes/SocketManager-Library-LogMessageEnum.html#method_array"
        },                {
            "fqsen": "\\SocketManager\\Library\\LogMessageEnum\u003A\u003ASOCKET_ERROR",
            "name": "SOCKET_ERROR",
            "summary": "",
            "url": "classes/SocketManager-Library-LogMessageEnum.html#enumcase_SOCKET_ERROR"
        },                {
            "fqsen": "\\SocketManager\\Library\\LogMessageEnum\u003A\u003AALIVE_CHECK_TIMEOUT",
            "name": "ALIVE_CHECK_TIMEOUT",
            "summary": "",
            "url": "classes/SocketManager-Library-LogMessageEnum.html#enumcase_ALIVE_CHECK_TIMEOUT"
        },                {
            "fqsen": "\\SocketManager\\Library\\LogMessageEnum\u003A\u003AALIVE_CHECK_START_TIMEOUT",
            "name": "ALIVE_CHECK_START_TIMEOUT",
            "summary": "",
            "url": "classes/SocketManager-Library-LogMessageEnum.html#enumcase_ALIVE_CHECK_START_TIMEOUT"
        },                {
            "fqsen": "\\SocketManager\\Library\\LogMessageEnum\u003A\u003ASOCKET_CREATE_FAIL",
            "name": "SOCKET_CREATE_FAIL",
            "summary": "",
            "url": "classes/SocketManager-Library-LogMessageEnum.html#enumcase_SOCKET_CREATE_FAIL"
        },                {
            "fqsen": "\\SocketManager\\Library\\LogMessageEnum\u003A\u003AQUEUE_START_FAIL",
            "name": "QUEUE_START_FAIL",
            "summary": "",
            "url": "classes/SocketManager-Library-LogMessageEnum.html#enumcase_QUEUE_START_FAIL"
        },                {
            "fqsen": "\\SocketManager\\Library\\LogMessageEnum\u003A\u003ASOCKET_OPTION_SETTING_FAIL",
            "name": "SOCKET_OPTION_SETTING_FAIL",
            "summary": "",
            "url": "classes/SocketManager-Library-LogMessageEnum.html#enumcase_SOCKET_OPTION_SETTING_FAIL"
        },                {
            "fqsen": "\\SocketManager\\Library\\LogMessageEnum\u003A\u003ASOCKET_NO_COUNT",
            "name": "SOCKET_NO_COUNT",
            "summary": "",
            "url": "classes/SocketManager-Library-LogMessageEnum.html#enumcase_SOCKET_NO_COUNT"
        },                {
            "fqsen": "\\SocketManager\\Library\\LogMessageEnum\u003A\u003ARECEIVE_SIZE_NO_SETTING",
            "name": "RECEIVE_SIZE_NO_SETTING",
            "summary": "",
            "url": "classes/SocketManager-Library-LogMessageEnum.html#enumcase_RECEIVE_SIZE_NO_SETTING"
        },                {
            "fqsen": "\\SocketManager\\Library\\LogMessageEnum\u003A\u003ASEND_DATA_NO_SETTING",
            "name": "SEND_DATA_NO_SETTING",
            "summary": "",
            "url": "classes/SocketManager-Library-LogMessageEnum.html#enumcase_SEND_DATA_NO_SETTING"
        },                {
            "fqsen": "\\SocketManager\\Library\\LogMessageEnum\u003A\u003AUNIT_NO_SETTING",
            "name": "UNIT_NO_SETTING",
            "summary": "",
            "url": "classes/SocketManager-Library-LogMessageEnum.html#enumcase_UNIT_NO_SETTING"
        },                {
            "fqsen": "\\SocketManager\\Library\\LogMessageEnum\u003A\u003ANONBLOCK_SETTING_FAIL",
            "name": "NONBLOCK_SETTING_FAIL",
            "summary": "",
            "url": "classes/SocketManager-Library-LogMessageEnum.html#enumcase_NONBLOCK_SETTING_FAIL"
        },                {
            "fqsen": "\\SocketManager\\Library\\ProtocolParameter",
            "name": "ProtocolParameter",
            "summary": "\u30D7\u30ED\u30C8\u30B3\u30EBUNIT\u30D1\u30E9\u30E1\u30FC\u30BF\u30AF\u30E9\u30B9",
            "url": "classes/SocketManager-Library-ProtocolParameter.html"
        },                {
            "fqsen": "\\SocketManager\\Library\\ProtocolParameter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "\u30B3\u30F3\u30B9\u30C8\u30E9\u30AF\u30BF",
            "url": "classes/SocketManager-Library-ProtocolParameter.html#method___construct"
        },                {
            "fqsen": "\\SocketManager\\Library\\ProtocolParameter\u003A\u003AsetSocketManagerParameter\u0028\u0029",
            "name": "setSocketManagerParameter",
            "summary": "SocketManagerParameter\u30A4\u30F3\u30B9\u30BF\u30F3\u30B9\u306E\u8A2D\u5B9A",
            "url": "classes/SocketManager-Library-ProtocolParameter.html#method_setSocketManagerParameter"
        },                {
            "fqsen": "\\SocketManager\\Library\\ProtocolParameter\u003A\u003AsetReceivingSize\u0028\u0029",
            "name": "setReceivingSize",
            "summary": "\u30C7\u30FC\u30BF\u53D7\u4FE1\u30B5\u30A4\u30BA\u306E\u8A2D\u5B9A",
            "url": "classes/SocketManager-Library-ProtocolParameter.html#method_setReceivingSize"
        },                {
            "fqsen": "\\SocketManager\\Library\\ProtocolParameter\u003A\u003Areceiving\u0028\u0029",
            "name": "receiving",
            "summary": "\u30C7\u30FC\u30BF\u53D7\u4FE1",
            "url": "classes/SocketManager-Library-ProtocolParameter.html#method_receiving"
        },                {
            "fqsen": "\\SocketManager\\Library\\ProtocolParameter\u003A\u003Arecv\u0028\u0029",
            "name": "recv",
            "summary": "\u30C7\u30FC\u30BF\u53D7\u4FE1",
            "url": "classes/SocketManager-Library-ProtocolParameter.html#method_recv"
        },                {
            "fqsen": "\\SocketManager\\Library\\ProtocolParameter\u003A\u003AsetSendingData\u0028\u0029",
            "name": "setSendingData",
            "summary": "\u9001\u4FE1\u30C7\u30FC\u30BF\u306E\u8A2D\u5B9A",
            "url": "classes/SocketManager-Library-ProtocolParameter.html#method_setSendingData"
        },                {
            "fqsen": "\\SocketManager\\Library\\ProtocolParameter\u003A\u003Asending\u0028\u0029",
            "name": "sending",
            "summary": "\u30C7\u30FC\u30BF\u9001\u4FE1",
            "url": "classes/SocketManager-Library-ProtocolParameter.html#method_sending"
        },                {
            "fqsen": "\\SocketManager\\Library\\ProtocolParameter\u003A\u003AgetSendData\u0028\u0029",
            "name": "getSendData",
            "summary": "\u51E6\u7406\u5BFE\u8C61\u306E\u9001\u4FE1\u30C7\u30FC\u30BF\u3092\u53D6\u5F97",
            "url": "classes/SocketManager-Library-ProtocolParameter.html#method_getSendData"
        },                {
            "fqsen": "\\SocketManager\\Library\\ProtocolParameter\u003A\u003A\u0024manager",
            "name": "manager",
            "summary": "",
            "url": "classes/SocketManager-Library-ProtocolParameter.html#property_manager"
        },                {
            "fqsen": "\\SocketManager\\Library\\ProtocolParameter\u003A\u003A\u0024param",
            "name": "param",
            "summary": "",
            "url": "classes/SocketManager-Library-ProtocolParameter.html#property_param"
        },                {
            "fqsen": "\\SocketManager\\Library\\ProtocolQueueEnum",
            "name": "ProtocolQueueEnum",
            "summary": "\u30D7\u30ED\u30C8\u30B3\u30EB\u90E8\u306E\u898F\u5B9A\u306E\u30AD\u30E5\u30FC\u540D\u5B9A\u7FA9",
            "url": "classes/SocketManager-Library-ProtocolQueueEnum.html"
        },                {
            "fqsen": "\\SocketManager\\Library\\ProtocolQueueEnum\u003A\u003AACCEPT",
            "name": "ACCEPT",
            "summary": "",
            "url": "classes/SocketManager-Library-ProtocolQueueEnum.html#enumcase_ACCEPT"
        },                {
            "fqsen": "\\SocketManager\\Library\\ProtocolQueueEnum\u003A\u003ACONNECT",
            "name": "CONNECT",
            "summary": "",
            "url": "classes/SocketManager-Library-ProtocolQueueEnum.html#enumcase_CONNECT"
        },                {
            "fqsen": "\\SocketManager\\Library\\ProtocolQueueEnum\u003A\u003ARECV",
            "name": "RECV",
            "summary": "",
            "url": "classes/SocketManager-Library-ProtocolQueueEnum.html#enumcase_RECV"
        },                {
            "fqsen": "\\SocketManager\\Library\\ProtocolQueueEnum\u003A\u003ASEND",
            "name": "SEND",
            "summary": "",
            "url": "classes/SocketManager-Library-ProtocolQueueEnum.html#enumcase_SEND"
        },                {
            "fqsen": "\\SocketManager\\Library\\ProtocolQueueEnum\u003A\u003ACLOSE",
            "name": "CLOSE",
            "summary": "",
            "url": "classes/SocketManager-Library-ProtocolQueueEnum.html#enumcase_CLOSE"
        },                {
            "fqsen": "\\SocketManager\\Library\\ProtocolQueueEnum\u003A\u003AALIVE",
            "name": "ALIVE",
            "summary": "",
            "url": "classes/SocketManager-Library-ProtocolQueueEnum.html#enumcase_ALIVE"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager",
            "name": "SocketManager",
            "summary": "\u30BD\u30B1\u30C3\u30C8\u30DE\u30CD\u30FC\u30B8\u30E3\u30FC\u30AF\u30E9\u30B9",
            "url": "classes/SocketManager-Library-SocketManager.html"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "\u30B3\u30F3\u30B9\u30C8\u30E9\u30AF\u30BF",
            "url": "classes/SocketManager-Library-SocketManager.html#method___construct"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AsetInitSocketManager\u0028\u0029",
            "name": "setInitSocketManager",
            "summary": "IInitSocketManager\u306B\u3088\u308B\u521D\u671F\u5316",
            "url": "classes/SocketManager-Library-SocketManager.html#method_setInitSocketManager"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AsetProtocolUnits\u0028\u0029",
            "name": "setProtocolUnits",
            "summary": "IEntryUnits\u306B\u3088\u308BUNIT\u767B\u9332\uFF08\u30D7\u30ED\u30C8\u30B3\u30EB\u7528\uFF09",
            "url": "classes/SocketManager-Library-SocketManager.html#method_setProtocolUnits"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AsetCommandUnits\u0028\u0029",
            "name": "setCommandUnits",
            "summary": "IEntryUnits\u306B\u3088\u308BUNIT\u767B\u9332\uFF08\u30B3\u30DE\u30F3\u30C9\u7528\uFF09",
            "url": "classes/SocketManager-Library-SocketManager.html#method_setCommandUnits"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AcycleDriven\u0028\u0029",
            "name": "cycleDriven",
            "summary": "\u5468\u671F\u30C9\u30EA\u30D6\u30F3\u51E6\u7406\u306E\u5B9F\u884C",
            "url": "classes/SocketManager-Library-SocketManager.html#method_cycleDriven"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AgetConnectionIdAll\u0028\u0029",
            "name": "getConnectionIdAll",
            "summary": "\u5168\u63A5\u7D9AID\u3092\u53D6\u5F97",
            "url": "classes/SocketManager-Library-SocketManager.html#method_getConnectionIdAll"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AgetQueueName\u0028\u0029",
            "name": "getQueueName",
            "summary": "\u30AD\u30E5\u30FC\u540D\u306E\u53D6\u5F97",
            "url": "classes/SocketManager-Library-SocketManager.html#method_getQueueName"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AgetStatusName\u0028\u0029",
            "name": "getStatusName",
            "summary": "\u30B9\u30C6\u30FC\u30BF\u30B9\u540D\u306E\u53D6\u5F97",
            "url": "classes/SocketManager-Library-SocketManager.html#method_getStatusName"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AsetStatusName\u0028\u0029",
            "name": "setStatusName",
            "summary": "\u30B9\u30C6\u30FC\u30BF\u30B9\u540D\u306E\u8A2D\u5B9A",
            "url": "classes/SocketManager-Library-SocketManager.html#method_setStatusName"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AisExecutedQueue\u0028\u0029",
            "name": "isExecutedQueue",
            "summary": "\u30AD\u30E5\u30FC\u306E\u5B9F\u884C\u72B6\u6CC1\u3092\u691C\u67FB",
            "url": "classes/SocketManager-Library-SocketManager.html#method_isExecutedQueue"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AaliveCheck\u0028\u0029",
            "name": "aliveCheck",
            "summary": "\u30A2\u30E9\u30A4\u30D6\u30C1\u30A7\u30C3\u30AF\u3092\u884C\u3046",
            "url": "classes/SocketManager-Library-SocketManager.html#method_aliveCheck"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AgetProperties\u0028\u0029",
            "name": "getProperties",
            "summary": "\u30D7\u30ED\u30D1\u30C6\u30A3\u306E\u53D6\u5F97\uFF08\u30C7\u30A3\u30B9\u30AF\u30EA\u30D7\u30BF\u5185\uFF09",
            "url": "classes/SocketManager-Library-SocketManager.html#method_getProperties"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AsetProperties\u0028\u0029",
            "name": "setProperties",
            "summary": "\u30D7\u30ED\u30D1\u30C6\u30A3\u306E\u8A2D\u5B9A\uFF08\u30C7\u30A3\u30B9\u30AF\u30EA\u30D7\u30BF\u5185\uFF09",
            "url": "classes/SocketManager-Library-SocketManager.html#method_setProperties"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AgetUserProperties\u0028\u0029",
            "name": "getUserProperties",
            "summary": "\u30E6\u30FC\u30B6\u30FC\u30D7\u30ED\u30D1\u30C6\u30A3\u306E\u53D6\u5F97\uFF08\u30C7\u30A3\u30B9\u30AF\u30EA\u30D7\u30BF\u5185\uFF09",
            "url": "classes/SocketManager-Library-SocketManager.html#method_getUserProperties"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AsetUserProperties\u0028\u0029",
            "name": "setUserProperties",
            "summary": "\u30E6\u30FC\u30B6\u30FC\u30D7\u30ED\u30D1\u30C6\u30A3\u306E\u8A2D\u5B9A\uFF08\u30C7\u30A3\u30B9\u30AF\u30EA\u30D7\u30BF\u5185\uFF09",
            "url": "classes/SocketManager-Library-SocketManager.html#method_setUserProperties"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AgetAwaitHost\u0028\u0029",
            "name": "getAwaitHost",
            "summary": "\u5F85\u3061\u53D7\u3051\u30DB\u30B9\u30C8\u540D\u3092\u53D6\u5F97",
            "url": "classes/SocketManager-Library-SocketManager.html#method_getAwaitHost"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AgetAwaitPort\u0028\u0029",
            "name": "getAwaitPort",
            "summary": "\u5F85\u3061\u53D7\u3051\u30DD\u30FC\u30C8\u756A\u53F7\u3092\u53D6\u5F97",
            "url": "classes/SocketManager-Library-SocketManager.html#method_getAwaitPort"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AgetAwaitConnectionId\u0028\u0029",
            "name": "getAwaitConnectionId",
            "summary": "\u5F85\u3061\u53D7\u3051\u30DD\u30FC\u30C8\u306E\u63A5\u7D9AID\u3092\u53D6\u5F97",
            "url": "classes/SocketManager-Library-SocketManager.html#method_getAwaitConnectionId"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AgetSerializer\u0028\u0029",
            "name": "getSerializer",
            "summary": "\u30B7\u30EA\u30A2\u30E9\u30A4\u30B6\u30FC\u306E\u53D6\u5F97",
            "url": "classes/SocketManager-Library-SocketManager.html#method_getSerializer"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AgetUnserializer\u0028\u0029",
            "name": "getUnserializer",
            "summary": "\u30A2\u30F3\u30B7\u30EA\u30A2\u30E9\u30A4\u30B6\u30FC\u306E\u53D6\u5F97",
            "url": "classes/SocketManager-Library-SocketManager.html#method_getUnserializer"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AisExistDescriptor\u0028\u0029",
            "name": "isExistDescriptor",
            "summary": "\u30BD\u30B1\u30C3\u30C8\u30C7\u30A3\u30B9\u30AF\u30EA\u30D7\u30BF\u306E\u5B58\u5728\u3092\u691C\u67FB",
            "url": "classes/SocketManager-Library-SocketManager.html#method_isExistDescriptor"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AgetClientCount\u0028\u0029",
            "name": "getClientCount",
            "summary": "\u73FE\u5728\u306E\u30AF\u30E9\u30A4\u30A2\u30F3\u30C8\u6570\u3092\u53D6\u5F97",
            "url": "classes/SocketManager-Library-SocketManager.html#method_getClientCount"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AlogWriter\u0028\u0029",
            "name": "logWriter",
            "summary": "\u30ED\u30B0\u51FA\u529B",
            "url": "classes/SocketManager-Library-SocketManager.html#method_logWriter"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "\u30BD\u30B1\u30C3\u30C8\u5207\u65AD\u30B7\u30FC\u30B1\u30F3\u30B9\u306E\u958B\u59CB",
            "url": "classes/SocketManager-Library-SocketManager.html#method_close"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AthrowBreak\u0028\u0029",
            "name": "throwBreak",
            "summary": "\u30D7\u30ED\u30C8\u30B3\u30EBUNIT\u51E6\u7406\u3092\u4E2D\u65AD\u3059\u308B",
            "url": "classes/SocketManager-Library-SocketManager.html#method_throwBreak"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003Aconnect\u0028\u0029",
            "name": "connect",
            "summary": "\u30BD\u30B1\u30C3\u30C8\u63A5\u7D9A",
            "url": "classes/SocketManager-Library-SocketManager.html#method_connect"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003Alisten\u0028\u0029",
            "name": "listen",
            "summary": "\u30BD\u30B1\u30C3\u30C8\u30EA\u30C3\u30B9\u30F3\uFF08TCP\u7528\uFF09",
            "url": "classes/SocketManager-Library-SocketManager.html#method_listen"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003Abind\u0028\u0029",
            "name": "bind",
            "summary": "\u30BD\u30B1\u30C3\u30C8\u30D0\u30A4\u30F3\u30C9\uFF08UDP\u7528\uFF09",
            "url": "classes/SocketManager-Library-SocketManager.html#method_bind"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003Aselect\u0028\u0029",
            "name": "select",
            "summary": "\u30BD\u30B1\u30C3\u30C8\u30BB\u30EC\u30AF\u30C8",
            "url": "classes/SocketManager-Library-SocketManager.html#method_select"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003Ashutdown\u0028\u0029",
            "name": "shutdown",
            "summary": "\u30BD\u30B1\u30C3\u30C8\u30AF\u30ED\u30FC\u30BA",
            "url": "classes/SocketManager-Library-SocketManager.html#method_shutdown"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AshutdownAll\u0028\u0029",
            "name": "shutdownAll",
            "summary": "\u30BD\u30B1\u30C3\u30C8\u5168\u30AF\u30ED\u30FC\u30BA",
            "url": "classes/SocketManager-Library-SocketManager.html#method_shutdownAll"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AsetReceivingSize\u0028\u0029",
            "name": "setReceivingSize",
            "summary": "\u30C7\u30FC\u30BF\u53D7\u4FE1\u30B5\u30A4\u30BA\u306E\u8A2D\u5B9A",
            "url": "classes/SocketManager-Library-SocketManager.html#method_setReceivingSize"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003Areceiving\u0028\u0029",
            "name": "receiving",
            "summary": "\u30C7\u30FC\u30BF\u53D7\u4FE1",
            "url": "classes/SocketManager-Library-SocketManager.html#method_receiving"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AisReceiving\u0028\u0029",
            "name": "isReceiving",
            "summary": "\uFF08receiving\u30E1\u30BD\u30C3\u30C9\u306B\u3088\u308B\uFF09\u30C7\u30FC\u30BF\u53D7\u4FE1\u4E2D\u306E\u691C\u67FB",
            "url": "classes/SocketManager-Library-SocketManager.html#method_isReceiving"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003Arecv\u0028\u0029",
            "name": "recv",
            "summary": "\u30C7\u30FC\u30BF\u53D7\u4FE1",
            "url": "classes/SocketManager-Library-SocketManager.html#method_recv"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AsetSendingData\u0028\u0029",
            "name": "setSendingData",
            "summary": "\u9001\u4FE1\u30C7\u30FC\u30BF\u306E\u8A2D\u5B9A",
            "url": "classes/SocketManager-Library-SocketManager.html#method_setSendingData"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003Asending\u0028\u0029",
            "name": "sending",
            "summary": "\u30C7\u30FC\u30BF\u9001\u4FE1",
            "url": "classes/SocketManager-Library-SocketManager.html#method_sending"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AisSending\u0028\u0029",
            "name": "isSending",
            "summary": "\uFF08sending\u30E1\u30BD\u30C3\u30C9\u306B\u3088\u308B\uFF09\u30C7\u30FC\u30BF\u9001\u4FE1\u4E2D\u306E\u691C\u67FB",
            "url": "classes/SocketManager-Library-SocketManager.html#method_isSending"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AgetRecvStack\u0028\u0029",
            "name": "getRecvStack",
            "summary": "\u53D7\u4FE1\u30C7\u30FC\u30BF\u30B9\u30BF\u30C3\u30AF\u304B\u3089\u53D6\u5F97",
            "url": "classes/SocketManager-Library-SocketManager.html#method_getRecvStack"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AsetRecvStack\u0028\u0029",
            "name": "setRecvStack",
            "summary": "\u53D7\u4FE1\u30C7\u30FC\u30BF\u30B9\u30BF\u30C3\u30AF\u3078\u8A2D\u5B9A",
            "url": "classes/SocketManager-Library-SocketManager.html#method_setRecvStack"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AgetSendStack\u0028\u0029",
            "name": "getSendStack",
            "summary": "\u9001\u4FE1\u30C7\u30FC\u30BF\u30B9\u30BF\u30C3\u30AF\u304B\u3089\u53D6\u5F97",
            "url": "classes/SocketManager-Library-SocketManager.html#method_getSendStack"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AsetSendStack\u0028\u0029",
            "name": "setSendStack",
            "summary": "\u9001\u4FE1\u30C7\u30FC\u30BF\u30B9\u30BF\u30C3\u30AF\u3078\u8A2D\u5B9A",
            "url": "classes/SocketManager-Library-SocketManager.html#method_setSendStack"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AsetSendStackAll\u0028\u0029",
            "name": "setSendStackAll",
            "summary": "\u5168\u63A5\u7D9A\u306E\u9001\u4FE1\u30C7\u30FC\u30BF\u30B9\u30BF\u30C3\u30AF\u3078\u8A2D\u5B9A",
            "url": "classes/SocketManager-Library-SocketManager.html#method_setSendStackAll"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AsetQueueNameForStart\u0028\u0029",
            "name": "setQueueNameForStart",
            "summary": "\u30AD\u30E5\u30FC\u540D\u306E\u8A2D\u5B9A\uFF08\u51E6\u7406\u958B\u59CB\u7528\uFF09",
            "url": "classes/SocketManager-Library-SocketManager.html#method_setQueueNameForStart"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AisExecutingSequence\u0028\u0029",
            "name": "isExecutingSequence",
            "summary": "UNIT\u5B9F\u884C\u4E2D\u306E\u691C\u67FB",
            "url": "classes/SocketManager-Library-SocketManager.html#method_isExecutingSequence"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AexecuteUnit\u0028\u0029",
            "name": "executeUnit",
            "summary": "UNIT\u306E\u5B9F\u884C",
            "url": "classes/SocketManager-Library-SocketManager.html#method_executeUnit"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AcreateDescriptor\u0028\u0029",
            "name": "createDescriptor",
            "summary": "\u30BD\u30B1\u30C3\u30C8\u30C7\u30A3\u30B9\u30AF\u30EA\u30D7\u30BF\u306E\u751F\u6210",
            "url": "classes/SocketManager-Library-SocketManager.html#method_createDescriptor"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003ASOCKET_ERROR_COULDNT_COMPLETED",
            "name": "SOCKET_ERROR_COULDNT_COMPLETED",
            "summary": "\u30BD\u30B1\u30C3\u30C8\u64CD\u4F5C\u3092\u5B8C\u4E86\u3067\u304D\u306A\u304B\u3063\u305F",
            "url": "classes/SocketManager-Library-SocketManager.html#constant_SOCKET_ERROR_COULDNT_COMPLETED"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003ASOCKET_ERROR_PEER_SHUTDOWN",
            "name": "SOCKET_ERROR_PEER_SHUTDOWN",
            "summary": "\u76F8\u624B\u5148\u306B\u3088\u308B\u5207\u65AD",
            "url": "classes/SocketManager-Library-SocketManager.html#constant_SOCKET_ERROR_PEER_SHUTDOWN"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AE_CLASS_NAME_FOR_UNIT",
            "name": "E_CLASS_NAME_FOR_UNIT",
            "summary": "EXCEPTION\u30AF\u30E9\u30B9\u540D\uFF08UNIT\u51E6\u7406\u7528\uFF09",
            "url": "classes/SocketManager-Library-SocketManager.html#constant_E_CLASS_NAME_FOR_UNIT"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003AUDP_CONNECTION_IDENTIFY",
            "name": "UDP_CONNECTION_IDENTIFY",
            "summary": "UDP\u63A5\u7D9A\u8B58\u5225\u30C7\u30FC\u30BF",
            "url": "classes/SocketManager-Library-SocketManager.html#constant_UDP_CONNECTION_IDENTIFY"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003A\u0024await_host",
            "name": "await_host",
            "summary": "\u5F85\u3061\u53D7\u3051\u7528\u30DB\u30B9\u30C8",
            "url": "classes/SocketManager-Library-SocketManager.html#property_await_host"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003A\u0024await_port",
            "name": "await_port",
            "summary": "\u5F85\u3061\u53D7\u3051\u7528\u30DD\u30FC\u30C8",
            "url": "classes/SocketManager-Library-SocketManager.html#property_await_port"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003A\u0024await_connection_id",
            "name": "await_connection_id",
            "summary": "\u5F85\u3061\u53D7\u3051\u7528\u30BD\u30B1\u30C3\u30C8\u306E\u63A5\u7D9AID",
            "url": "classes/SocketManager-Library-SocketManager.html#property_await_connection_id"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003A\u0024receive_buffer_size",
            "name": "receive_buffer_size",
            "summary": "\u53D7\u4FE1\u30B5\u30A4\u30BA\uFF08recv\u30E1\u30BD\u30C3\u30C9\u306E\u30C7\u30D5\u30A9\u30EB\u30C8\u53D7\u4FE1\u30B5\u30A4\u30BA\uFF09",
            "url": "classes/SocketManager-Library-SocketManager.html#property_receive_buffer_size"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003A\u0024descriptors",
            "name": "descriptors",
            "summary": "\u3010\u30C7\u30A3\u30B9\u30AF\u30EA\u30D7\u30BF\u306E\u30EA\u30B9\u30C8\u3011",
            "url": "classes/SocketManager-Library-SocketManager.html#property_descriptors"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003A\u0024sockets",
            "name": "sockets",
            "summary": "\u30BD\u30B1\u30C3\u30C8\u30EA\u30BD\u30FC\u30B9\u306E\u30EA\u30B9\u30C8",
            "url": "classes/SocketManager-Library-SocketManager.html#property_sockets"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003A\u0024changed_descriptors",
            "name": "changed_descriptors",
            "summary": "\u524D\u56DE\u306ESELECT\u72B6\u614B\u304C\u683C\u7D0D\u3055\u308C\u308B",
            "url": "classes/SocketManager-Library-SocketManager.html#property_changed_descriptors"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003A\u0024cycle_driven_for_protocol",
            "name": "cycle_driven_for_protocol",
            "summary": "\u5468\u671F\u30C9\u30EA\u30D6\u30F3\u30DE\u30CD\u30FC\u30B8\u30E3\u30FC\uFF08\u30D7\u30ED\u30C8\u30B3\u30EBUNIT\u7528\uFF09",
            "url": "classes/SocketManager-Library-SocketManager.html#property_cycle_driven_for_protocol"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003A\u0024cycle_driven_for_command",
            "name": "cycle_driven_for_command",
            "summary": "\u5468\u671F\u30C9\u30EA\u30D6\u30F3\u30DE\u30CD\u30FC\u30B8\u30E3\u30FC\uFF08\u30B3\u30DE\u30F3\u30C9UNIT\u7528\uFF09",
            "url": "classes/SocketManager-Library-SocketManager.html#property_cycle_driven_for_command"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003A\u0024unit_parameter",
            "name": "unit_parameter",
            "summary": "SocketManager\u7528\u3068\u3057\u3066\u6271\u3046UNIT\u30D1\u30E9\u30E1\u30FC\u30BF",
            "url": "classes/SocketManager-Library-SocketManager.html#property_unit_parameter"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003A\u0024log_writer",
            "name": "log_writer",
            "summary": "\u30ED\u30B0\u30E9\u30A4\u30BF\u30FC",
            "url": "classes/SocketManager-Library-SocketManager.html#property_log_writer"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003A\u0024serializer",
            "name": "serializer",
            "summary": "\u30B7\u30EA\u30A2\u30E9\u30A4\u30B6\u30FC",
            "url": "classes/SocketManager-Library-SocketManager.html#property_serializer"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003A\u0024unserializer",
            "name": "unserializer",
            "summary": "\u30A2\u30F3\u30B7\u30EA\u30A2\u30E9\u30A4\u30B6\u30FC",
            "url": "classes/SocketManager-Library-SocketManager.html#property_unserializer"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003A\u0024command_dispatcher",
            "name": "command_dispatcher",
            "summary": "\u30B3\u30DE\u30F3\u30C9\u30C7\u30A3\u30B9\u30D1\u30C3\u30C1\u30E3\u30FC",
            "url": "classes/SocketManager-Library-SocketManager.html#property_command_dispatcher"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003A\u0024emergency_callback",
            "name": "emergency_callback",
            "summary": "\u7DCA\u6025\u505C\u6B62\u6642\u306E\u30B3\u30FC\u30EB\u30D0\u30C3\u30AF",
            "url": "classes/SocketManager-Library-SocketManager.html#property_emergency_callback"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003A\u0024next_connection_id",
            "name": "next_connection_id",
            "summary": "NEXT\u63A5\u7D9AID",
            "url": "classes/SocketManager-Library-SocketManager.html#property_next_connection_id"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003A\u0024lang",
            "name": "lang",
            "summary": "\u8A00\u8A9E\u8A2D\u5B9A",
            "url": "classes/SocketManager-Library-SocketManager.html#property_lang"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManager\u003A\u003A\u0024limit_connection",
            "name": "limit_connection",
            "summary": "\u5236\u9650\u63A5\u7D9A\u6570",
            "url": "classes/SocketManager-Library-SocketManager.html#property_limit_connection"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter",
            "name": "SocketManagerParameter",
            "summary": "UNIT\u30D1\u30E9\u30E1\u30FC\u30BF\u306E\u57FA\u5E95\u30AF\u30E9\u30B9",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "\u30B3\u30F3\u30B9\u30C8\u30E9\u30AF\u30BF",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#method___construct"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003AgetQueueName\u0028\u0029",
            "name": "getQueueName",
            "summary": "\u30AD\u30E5\u30FC\u540D\u306E\u53D6\u5F97",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#method_getQueueName"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003AgetStatusName\u0028\u0029",
            "name": "getStatusName",
            "summary": "\u30B9\u30C6\u30FC\u30BF\u30B9\u540D\u306E\u53D6\u5F97",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#method_getStatusName"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003AsetStatusName\u0028\u0029",
            "name": "setStatusName",
            "summary": "\u30B9\u30C6\u30FC\u30BF\u30B9\u540D\u306E\u8A2D\u5B9A",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#method_setStatusName"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003AgetRecvData\u0028\u0029",
            "name": "getRecvData",
            "summary": "\u51E6\u7406\u5BFE\u8C61\u306E\u53D7\u4FE1\u30C7\u30FC\u30BF\u3092\u53D6\u5F97",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#method_getRecvData"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003AsetRecvData\u0028\u0029",
            "name": "setRecvData",
            "summary": "\u51E6\u7406\u5BFE\u8C61\u306E\u53D7\u4FE1\u30C7\u30FC\u30BF\u3092\u8A2D\u5B9A",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#method_setRecvData"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003AsetRecvStack\u0028\u0029",
            "name": "setRecvStack",
            "summary": "\u53D7\u4FE1\u30C7\u30FC\u30BF\u30B9\u30BF\u30C3\u30AF\u3078\u8A2D\u5B9A",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#method_setRecvStack"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003AsetSendStack\u0028\u0029",
            "name": "setSendStack",
            "summary": "\u9001\u4FE1\u30C7\u30FC\u30BF\u30B9\u30BF\u30C3\u30AF\u3078\u8A2D\u5B9A",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#method_setSendStack"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003AsetSendStackAll\u0028\u0029",
            "name": "setSendStackAll",
            "summary": "\u5168\u63A5\u7D9A\u306E\u9001\u4FE1\u30C7\u30FC\u30BF\u30B9\u30BF\u30C3\u30AF\u3078\u8A2D\u5B9A",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#method_setSendStackAll"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "\u5207\u65AD\u30B7\u30FC\u30B1\u30F3\u30B9\u958B\u59CB\uFF08\u30D7\u30ED\u30C8\u30B3\u30EB\u30E6\u30CB\u30C3\u30C8\u306E\u0027CLOSE\u0027\u30AD\u30E5\u30FC\u3092\u5B9F\u884C\uFF09",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#method_close"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003AgetCloseParameter\u0028\u0029",
            "name": "getCloseParameter",
            "summary": "\u5207\u65AD\u30D1\u30E9\u30E1\u30FC\u30BF\uFF08\u5207\u65AD\u30B7\u30FC\u30B1\u30F3\u30B9\u306B\u3088\u3063\u3066\u767B\u9332\u3055\u308C\u305F\u30D1\u30E9\u30E1\u30FC\u30BF\uFF09\u306E\u53D6\u5F97",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#method_getCloseParameter"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003AthrowBreak\u0028\u0029",
            "name": "throwBreak",
            "summary": "\u30D7\u30ED\u30C8\u30B3\u30EBUNIT\u51E6\u7406\u3092\u4E2D\u65AD\u3059\u308B",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#method_throwBreak"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003AemergencyShutdown\u0028\u0029",
            "name": "emergencyShutdown",
            "summary": "\u7DCA\u6025\u505C\u6B62\uFF08\u5373\u6642\u5207\u65AD\uFF09",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#method_emergencyShutdown"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003AlogWriter\u0028\u0029",
            "name": "logWriter",
            "summary": "\u30ED\u30B0\u30E9\u30A4\u30BF\u30FC",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#method_logWriter"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003AisExecutedQueue\u0028\u0029",
            "name": "isExecutedQueue",
            "summary": "\u30AD\u30E5\u30FC\u306E\u5B9F\u884C\u72B6\u6CC1\u3092\u691C\u67FB",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#method_isExecutedQueue"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003AaliveCheck\u0028\u0029",
            "name": "aliveCheck",
            "summary": "\u30A2\u30E9\u30A4\u30D6\u30C1\u30A7\u30C3\u30AF\u3092\u884C\u3046",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#method_aliveCheck"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003AgetAwaitConnectionId\u0028\u0029",
            "name": "getAwaitConnectionId",
            "summary": "\u5F85\u3061\u53D7\u3051\u30DD\u30FC\u30C8\u306E\u63A5\u7D9AID\u306E\u53D6\u5F97",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#method_getAwaitConnectionId"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003AgetClientCount\u0028\u0029",
            "name": "getClientCount",
            "summary": "\u73FE\u5728\u306E\u30E6\u30FC\u30B6\u30FC\u6570\u3092\u53D6\u5F97",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#method_getClientCount"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003AgetTempBuff\u0028\u0029",
            "name": "getTempBuff",
            "summary": "\u30C6\u30F3\u30DD\u30E9\u30EA\u30D0\u30C3\u30D5\u30A1\u306E\u53D6\u5F97",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#method_getTempBuff"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003AsetTempBuff\u0028\u0029",
            "name": "setTempBuff",
            "summary": "\u30C6\u30F3\u30DD\u30E9\u30EA\u30D0\u30C3\u30D5\u30A1\u306E\u8A2D\u5B9A",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#method_setTempBuff"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003AgetAwaitHost\u0028\u0029",
            "name": "getAwaitHost",
            "summary": "\u5F85\u3061\u53D7\u3051\u30DB\u30B9\u30C8\u540D\u3092\u53D6\u5F97",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#method_getAwaitHost"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003AgetAwaitPort\u0028\u0029",
            "name": "getAwaitPort",
            "summary": "\u5F85\u3061\u53D7\u3051\u30DD\u30FC\u30C8\u756A\u53F7\u3092\u53D6\u5F97",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#method_getAwaitPort"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003AisReceiving\u0028\u0029",
            "name": "isReceiving",
            "summary": "\u30C7\u30FC\u30BF\u53D7\u4FE1\u4E2D\u306E\u691C\u67FB",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#method_isReceiving"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003AisSending\u0028\u0029",
            "name": "isSending",
            "summary": "\u30C7\u30FC\u30BF\u9001\u4FE1\u4E2D\u306E\u691C\u67FB",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#method_isSending"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003AgetLanguage\u0028\u0029",
            "name": "getLanguage",
            "summary": "\u8A00\u8A9E\u30B3\u30FC\u30C9\u306E\u53D6\u5F97",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#method_getLanguage"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003AsetLanguage\u0028\u0029",
            "name": "setLanguage",
            "summary": "\u8A00\u8A9E\u30B3\u30FC\u30C9\u306E\u8A2D\u5B9A",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#method_setLanguage"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003AgetSocketManager\u0028\u0029",
            "name": "getSocketManager",
            "summary": "\u30BD\u30B1\u30C3\u30C8\u30DE\u30CD\u30FC\u30B8\u30E3\u30FC\u306E\u53D6\u5F97",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#method_getSocketManager"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003AsetSocketManager\u0028\u0029",
            "name": "setSocketManager",
            "summary": "\u30BD\u30B1\u30C3\u30C8\u30DE\u30CD\u30FC\u30B8\u30E3\u30FC\u306E\u8A2D\u5B9A",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#method_setSocketManager"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003AgetKindString\u0028\u0029",
            "name": "getKindString",
            "summary": "\u5468\u671F\u30C9\u30EA\u30D6\u30F3\u30DE\u30CD\u30FC\u30B8\u30E3\u30FC\u306E\u7A2E\u5225\u53D6\u5F97",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#method_getKindString"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003AsetKindString\u0028\u0029",
            "name": "setKindString",
            "summary": "\u5468\u671F\u30C9\u30EA\u30D6\u30F3\u30DE\u30CD\u30FC\u30B8\u30E3\u30FC\u306E\u7A2E\u5225\u8A2D\u5B9A",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#method_setKindString"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003AgetConnectionId\u0028\u0029",
            "name": "getConnectionId",
            "summary": "\u63A5\u7D9AID\u306E\u53D6\u5F97",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#method_getConnectionId"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003AsetConnectionId\u0028\u0029",
            "name": "setConnectionId",
            "summary": "\u63A5\u7D9AID\u306E\u8A2D\u5B9A",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#method_setConnectionId"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003A\u0024protocol",
            "name": "protocol",
            "summary": "\u30D7\u30ED\u30C8\u30B3\u30EBUNIT\u30D1\u30E9\u30E1\u30FC\u30BF",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#property_protocol"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "getter\u30E1\u30BD\u30C3\u30C9\u306E\u547C\u3073\u51FA\u3057",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#method___get"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003A\u0024manager",
            "name": "manager",
            "summary": "\u30BD\u30B1\u30C3\u30C8\u30DE\u30CD\u30FC\u30B8\u30E3\u30FC",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#property_manager"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003A\u0024kind",
            "name": "kind",
            "summary": "\u5468\u671F\u30C9\u30EA\u30D6\u30F3\u30DE\u30CD\u30FC\u30B8\u30E3\u30FC\u306E\u7A2E\u5225\n\u0027protocol_names\u0027\u0020or\u0020\u0027command_names\u0027",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#property_kind"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003A\u0024cid",
            "name": "cid",
            "summary": "\u63A5\u7D9AID",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#property_cid"
        },                {
            "fqsen": "\\SocketManager\\Library\\SocketManagerParameter\u003A\u003A\u0024lang",
            "name": "lang",
            "summary": "\u8A00\u8A9E\u8A2D\u5B9A",
            "url": "classes/SocketManager-Library-SocketManagerParameter.html#property_lang"
        },                {
            "fqsen": "\\SocketManager\\Library\\StatusEnum",
            "name": "StatusEnum",
            "summary": "UNIT\u306E\u898F\u5B9A\u306E\u30B9\u30C6\u30FC\u30BF\u30B9\u540D\u5B9A\u7FA9",
            "url": "classes/SocketManager-Library-StatusEnum.html"
        },                {
            "fqsen": "\\SocketManager\\Library\\StatusEnum\u003A\u003ASTART",
            "name": "START",
            "summary": "",
            "url": "classes/SocketManager-Library-StatusEnum.html#enumcase_START"
        },                {
            "fqsen": "\\SocketManager\\Library\\UnitException",
            "name": "UnitException",
            "summary": "Exception\u30AF\u30E9\u30B9",
            "url": "classes/SocketManager-Library-UnitException.html"
        },                {
            "fqsen": "\\SocketManager\\Library\\UnitException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "\u30B3\u30F3\u30B9\u30C8\u30E9\u30AF\u30BF",
            "url": "classes/SocketManager-Library-UnitException.html#method___construct"
        },                {
            "fqsen": "\\SocketManager\\Library\\UnitException\u003A\u003AgetIdentifier\u0028\u0029",
            "name": "getIdentifier",
            "summary": "\u4F8B\u5916\u8B58\u5225\u5B50\u306E\u53D6\u5F97",
            "url": "classes/SocketManager-Library-UnitException.html#method_getIdentifier"
        },                {
            "fqsen": "\\SocketManager\\Library\\UnitException\u003A\u003AgetArrayMessage\u0028\u0029",
            "name": "getArrayMessage",
            "summary": "\u4F8B\u5916\u30E1\u30C3\u30BB\u30FC\u30B8\u914D\u5217\u306E\u53D6\u5F97",
            "url": "classes/SocketManager-Library-UnitException.html#method_getArrayMessage"
        },                {
            "fqsen": "\\SocketManager\\Library\\UnitException\u003A\u003A\u0024param",
            "name": "param",
            "summary": "",
            "url": "classes/SocketManager-Library-UnitException.html#property_param"
        },                {
            "fqsen": "\\SocketManager\\Library\\UnitExceptionEnum",
            "name": "UnitExceptionEnum",
            "summary": "\u4F8B\u5916\u30B3\u30FC\u30C9\u5B9A\u7FA9",
            "url": "classes/SocketManager-Library-UnitExceptionEnum.html"
        },                {
            "fqsen": "\\SocketManager\\Library\\UnitExceptionEnum\u003A\u003Amessage\u0028\u0029",
            "name": "message",
            "summary": "\u4F8B\u5916\u30E1\u30C3\u30BB\u30FC\u30B8\u306E\u53D6\u5F97",
            "url": "classes/SocketManager-Library-UnitExceptionEnum.html#method_message"
        },                {
            "fqsen": "\\SocketManager\\Library\\UnitExceptionEnum\u003A\u003AECODE_HANDSHAKE_FAIL",
            "name": "ECODE_HANDSHAKE_FAIL",
            "summary": "",
            "url": "classes/SocketManager-Library-UnitExceptionEnum.html#enumcase_ECODE_HANDSHAKE_FAIL"
        },                {
            "fqsen": "\\SocketManager\\Library\\UnitExceptionEnum\u003A\u003AECODE_USER_PROPERTY_GET_FAIL",
            "name": "ECODE_USER_PROPERTY_GET_FAIL",
            "summary": "",
            "url": "classes/SocketManager-Library-UnitExceptionEnum.html#enumcase_ECODE_USER_PROPERTY_GET_FAIL"
        },                {
            "fqsen": "\\SocketManager\\Library\\UnitExceptionEnum\u003A\u003AECODE_USER_PROPERTY_SET_FAIL",
            "name": "ECODE_USER_PROPERTY_SET_FAIL",
            "summary": "",
            "url": "classes/SocketManager-Library-UnitExceptionEnum.html#enumcase_ECODE_USER_PROPERTY_SET_FAIL"
        },                {
            "fqsen": "\\SocketManager\\Library\\UnitExceptionEnum\u003A\u003AECODE_PROPERTY_GET_FAIL",
            "name": "ECODE_PROPERTY_GET_FAIL",
            "summary": "",
            "url": "classes/SocketManager-Library-UnitExceptionEnum.html#enumcase_ECODE_PROPERTY_GET_FAIL"
        },                {
            "fqsen": "\\SocketManager\\Library\\UnitExceptionEnum\u003A\u003AECODE_PROPERTY_SET_FAIL",
            "name": "ECODE_PROPERTY_SET_FAIL",
            "summary": "",
            "url": "classes/SocketManager-Library-UnitExceptionEnum.html#enumcase_ECODE_PROPERTY_SET_FAIL"
        },                {
            "fqsen": "\\SocketManager\\Library\\UnitExceptionEnum\u003A\u003AECODE_RECEIVING_SIZE_SET_FAIL",
            "name": "ECODE_RECEIVING_SIZE_SET_FAIL",
            "summary": "",
            "url": "classes/SocketManager-Library-UnitExceptionEnum.html#enumcase_ECODE_RECEIVING_SIZE_SET_FAIL"
        },                {
            "fqsen": "\\SocketManager\\Library\\UnitExceptionEnum\u003A\u003AECODE_RECEIVING_FAIL",
            "name": "ECODE_RECEIVING_FAIL",
            "summary": "",
            "url": "classes/SocketManager-Library-UnitExceptionEnum.html#enumcase_ECODE_RECEIVING_FAIL"
        },                {
            "fqsen": "\\SocketManager\\Library\\UnitExceptionEnum\u003A\u003AECODE_RECEIVE_DATA_STACK_FAIL",
            "name": "ECODE_RECEIVE_DATA_STACK_FAIL",
            "summary": "",
            "url": "classes/SocketManager-Library-UnitExceptionEnum.html#enumcase_ECODE_RECEIVE_DATA_STACK_FAIL"
        },                {
            "fqsen": "\\SocketManager\\Library\\UnitExceptionEnum\u003A\u003AECODE_SENDING_DATA_SET_FAIL",
            "name": "ECODE_SENDING_DATA_SET_FAIL",
            "summary": "",
            "url": "classes/SocketManager-Library-UnitExceptionEnum.html#enumcase_ECODE_SENDING_DATA_SET_FAIL"
        },                {
            "fqsen": "\\SocketManager\\Library\\UnitExceptionEnum\u003A\u003AECODE_SENDING_FAIL",
            "name": "ECODE_SENDING_FAIL",
            "summary": "",
            "url": "classes/SocketManager-Library-UnitExceptionEnum.html#enumcase_ECODE_SENDING_FAIL"
        },                {
            "fqsen": "\\SocketManager\\Library\\UnitExceptionEnum\u003A\u003AECODE_PICKUP_RECEIVE_DATA_GET_FAIL",
            "name": "ECODE_PICKUP_RECEIVE_DATA_GET_FAIL",
            "summary": "",
            "url": "classes/SocketManager-Library-UnitExceptionEnum.html#enumcase_ECODE_PICKUP_RECEIVE_DATA_GET_FAIL"
        },                {
            "fqsen": "\\SocketManager\\Library\\UnitExceptionEnum\u003A\u003AECODE_PICKUP_RECEIVE_DATA_SET_FAIL",
            "name": "ECODE_PICKUP_RECEIVE_DATA_SET_FAIL",
            "summary": "",
            "url": "classes/SocketManager-Library-UnitExceptionEnum.html#enumcase_ECODE_PICKUP_RECEIVE_DATA_SET_FAIL"
        },                {
            "fqsen": "\\SocketManager\\Library\\UnitExceptionEnum\u003A\u003AECODE_PICKUP_SEND_DATA_GET_FAIL",
            "name": "ECODE_PICKUP_SEND_DATA_GET_FAIL",
            "summary": "",
            "url": "classes/SocketManager-Library-UnitExceptionEnum.html#enumcase_ECODE_PICKUP_SEND_DATA_GET_FAIL"
        },                {
            "fqsen": "\\SocketManager\\Library\\UnitExceptionEnum\u003A\u003AECODE_METHOD_CALL_FAIL",
            "name": "ECODE_METHOD_CALL_FAIL",
            "summary": "",
            "url": "classes/SocketManager-Library-UnitExceptionEnum.html#enumcase_ECODE_METHOD_CALL_FAIL"
        },                {
            "fqsen": "\\SocketManager\\Library\\UnitExceptionEnum\u003A\u003AECODE_SEND_DATA_STACK_FAIL",
            "name": "ECODE_SEND_DATA_STACK_FAIL",
            "summary": "",
            "url": "classes/SocketManager-Library-UnitExceptionEnum.html#enumcase_ECODE_SEND_DATA_STACK_FAIL"
        },                {
            "fqsen": "\\SocketManager\\Library\\UnitExceptionEnum\u003A\u003AECODE_CLOSE_FAIL",
            "name": "ECODE_CLOSE_FAIL",
            "summary": "",
            "url": "classes/SocketManager-Library-UnitExceptionEnum.html#enumcase_ECODE_CLOSE_FAIL"
        },                {
            "fqsen": "\\SocketManager\\Library\\UnitExceptionEnum\u003A\u003AECODE_EX_MESSAGE_GET_FAIL",
            "name": "ECODE_EX_MESSAGE_GET_FAIL",
            "summary": "",
            "url": "classes/SocketManager-Library-UnitExceptionEnum.html#enumcase_ECODE_EX_MESSAGE_GET_FAIL"
        },                {
            "fqsen": "\\SocketManager\\Library\\UnitExceptionEnum\u003A\u003AECODE_COMMAND_MISMATCH",
            "name": "ECODE_COMMAND_MISMATCH",
            "summary": "",
            "url": "classes/SocketManager-Library-UnitExceptionEnum.html#enumcase_ECODE_COMMAND_MISMATCH"
        },                {
            "fqsen": "\\SocketManager\\Library\\UnitExceptionEnum\u003A\u003AECODE_ALIVE_CHECK_FAIL",
            "name": "ECODE_ALIVE_CHECK_FAIL",
            "summary": "",
            "url": "classes/SocketManager-Library-UnitExceptionEnum.html#enumcase_ECODE_ALIVE_CHECK_FAIL"
        },                {
            "fqsen": "\\SocketManager\\Library\\UnitExceptionEnum\u003A\u003AECODE_EMERGENCY_SHUTDOWN",
            "name": "ECODE_EMERGENCY_SHUTDOWN",
            "summary": "",
            "url": "classes/SocketManager-Library-UnitExceptionEnum.html#enumcase_ECODE_EMERGENCY_SHUTDOWN"
        },                {
            "fqsen": "\\SocketManager\\Library\\UnitExceptionEnum\u003A\u003AECODE_THROW_BREAK",
            "name": "ECODE_THROW_BREAK",
            "summary": "",
            "url": "classes/SocketManager-Library-UnitExceptionEnum.html#enumcase_ECODE_THROW_BREAK"
        },                {
            "fqsen": "\\SocketManager\\Library\\UnitExceptionEnum\u003A\u003AECODE_REQUEST_CLOSE",
            "name": "ECODE_REQUEST_CLOSE",
            "summary": "",
            "url": "classes/SocketManager-Library-UnitExceptionEnum.html#enumcase_ECODE_REQUEST_CLOSE"
        },                {
            "fqsen": "\\SocketManager\\Library\\UnitExceptionEnum\u003A\u003AECODE_FORCE_CLOSE",
            "name": "ECODE_FORCE_CLOSE",
            "summary": "",
            "url": "classes/SocketManager-Library-UnitExceptionEnum.html#enumcase_ECODE_FORCE_CLOSE"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\SocketManager\\Library",
            "name": "Library",
            "summary": "",
            "url": "namespaces/socketmanager-library.html"
        },                {
            "fqsen": "\\SocketManager",
            "name": "SocketManager",
            "summary": "",
            "url": "namespaces/socketmanager.html"
        }            ]
);
